config/routes.rb
BlogOnRails::Application.routes.draw do
  devise_for :users

  resources :articles, :only => [:index, :show]

  root :to => "articles#index"
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :content, :parent, :parent_id, :author
  belongs_to :parent, :class_name => "Article"
  belongs_to :author, :class_name => "User"
  has_many :replies,  :class_name => "Article",
                      :foreign_key => "parent_id"

  has_paper_trail

  def rendered
    if content.match(/^\.\. -\*- mode: rst -\*-\r\n\r\n/)
      Net::HTTP.post_form( URI.parse('http://restructuredtext.appspot.com/api/v1/rst2html/'), {
          :rst => self.content
      }).body.html_safe
    else
      self.content.html_safe
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :display_name

  has_paper_trail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  respond_to :html, :js
end

app/controllers/articles_controller.rb
class ArticlesController < InheritedResources::Base
protected
  def collection
    @articles ||= end_of_association_chain.
                      where(:parent_id => nil).
                      order("created_at DESC").
                      offset(params[:offset]).
                      limit(2)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def next_posts(created_at, limit = 4)
    Article.where(:parent_id => nil).
            order("created_at ASC").
            where("created_at > ?", created_at).
            limit(limit)
  end

  def prev_posts(created_at, limit = 5)
    Article.where(:parent_id => nil).
            order("created_at DESC").
            where("created_at < ?", created_at).
            limit(limit)
  end

end

app/views/articles/_form.html.haml
= simple_form_for article do |f|
  - if article.errors.any?
    #error_explanation
      %h2
        = pluralize(article.errors.count, "error")
        prohibited this article from being saved:

      %ul
      - article.errors.full_messages.each do |msg|
        %li= msg

  .inputs
    = f.input :title
    = f.input :content
    = f.association :parent, :as => :hidden

  .actions
    = f.button :submit

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form', :article => @article

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
- @articles.each do |article|
  %article
    %h1= link_to article.title, article
    %section= article.rendered
    %ul.meta
      /%li= article.parent && article.parent.title
      %li= article.author || "Anonymous"
      %li= link_to 'Leave a comment', article_path(article, :anchor => "reply")
      %li no tags (yet)
      %li Posted #{article.created_at.strftime("on %a, %d %b %Y at %H:%M")}
      /%li= link_to 'Edit', edit_article_path(article)
      /%li= link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete

- content_for :recently do
  %ul
    - next_posts = next_posts(@articles.first.created_at).reverse
    - next_posts.each do |article|
      %li.current
        = link_to article do
          %span.date= article.created_at.strftime("%m.%d")
          = article.title
    - @articles.each do |article|
      %li.current
        = link_to article do
          %span.date= article.created_at.strftime("%m.%d")
          = article.title
    -prev_posts = prev_posts(@articles.last.created_at, 8 - next_posts.count)
    -prev_posts.each do |article|
      %li.current
        = link_to article do
          %span.date= article.created_at.strftime("%m.%d")
          = article.title
- content_for :head do
  =stylesheet_link_tag 'index'

app/views/articles/new.html.haml
%h1 New article

= render 'form', :article => @article

= link_to 'Back', articles_path

app/views/articles/show.html.haml
%aside
  %section
    %h1 About this article
    %p You're currently reading "#{@article.title}", an entry on LoonyBin
    -if @article.parent
      %dl
        %dt Parent
        %dd= link_to @article.parent.title, @article.parent
    %dl
      %dt Author
      %dd= @article.author || "anonymous"
    %dl
      %dt Published
      %dd= @article.created_at
      //%li= link_to 'Edit', edit_article_path(@article)
    %p= link_to 'Back', articles_path
%article
  %h1= @article.title
  %section= @article.rendered

-content_for :ancillary do
  %aside=# render 'form', :article => Article.new( :parent => @article, :title => 'Re: ' + @article.title )
  #comments
    - @article.replies.each do |reply|
      %article
        %h4= reply.title
        %section= reply.rendered
        %ul.meta
          %li= reply.author
          %li= reply.created_at
          %li= link_to 'Show', reply
-content_for :recently do
  %ul
    -next_posts = next_posts(@article.created_at).reverse
    -next_posts.each do |article|
      %li
        = link_to article do
          %span.date= article.created_at.strftime("%m.%d")
          = article.title
    %li.current
      %span.date= @article.created_at.strftime("%m.%d")
      = @article.title
    -prev_posts = prev_posts(@article.created_at, 9 - next_posts.count)
    -prev_posts.each do |article|
      %li
        = link_to article do
          %span.date= article.created_at.strftime("%m.%d")
          = article.title

-content_for :head do
  =stylesheet_link_tag 'show'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title LoonyBin

    = javascript_include_tag :defaults

    = stylesheet_link_tag 'screen.css', :media => 'screen, projection'
    = stylesheet_link_tag 'print.css', :media => 'print'
    /[if IE]
      = stylesheet_link_tag 'ie.css', :media => 'screen, projection'
    = stylesheet_link_tag 'application.css'
    = stylesheet_link_tag 'friendly.css'

    = csrf_meta_tag
    = yield :head
  %body
    %header
      %hgroup#title
        %h1= link_to 'LoonyBin', root_url
        %h2 Technology won't solve every problem; Crazyness might...
      %hgroup#search
        =form_tag 'http://google.com/search', :method => :get do
          =search_field_tag :q, nil, :class => 'text'
          =hidden_field_tag :sitesearch, "http://loonyb.in/"
          =submit_tag :search
    .main
      =yield
    .ancillary
      =yield :ancillary
    %aside
      %section.left
        %h1 About
      %section.center
        %h1 Tags
      %section.right
        %h1 Recently
        =yield :recently
    %footer
      %p All rights reserved &copy; 2010, LoonyBin